
spring:
  datasource:
    password: mylove4u
    url: jdbc:postgresql://localhost:5432/AI_learning
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 6MB